substitutions:
    name: esp32-bluetooth-proxy-2c540c
    friendly_name: Bluetooth Proxy 2c540c
    id_ble_client1:
packages:
    esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esphome:
    name: gbt-ble-proxy

esp32:
    board: esp32dev
    framework:
        type: arduino
# Enable logging

logger:
    level: VERBOSE

# Enable Home Assistant API
api:
    encryption:
        key: 'G87xToEZl+slSd3zABa0gFdTSECft49itcG2+ijZukM='

ota:
    - platform: esphome
      password: 'd610ed309a79c724406c68c094316693'

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
        ssid: 'Bluetooth-Proxy-Test'
        password: '1WP9dKawnoWr'

captive_portal:

esp32_ble_tracker:
    scan_parameters:
        interval: 1100ms
        window: 1100ms
        active: true

bluetooth_proxy:
    active: true

ble_client:
    # Replace with the MAC address of your device.
    - mac_address: FF:FF:20:00:0F:15
      id: itag_white

binary_sensor:
    - platform: template
      id: white_button
      name: 'White iTag Button'
      filters:
          delayed_off: 200ms

sensor:
    # This entry registers and awaits notifications for the
    # characteristic that signals button presses. Each time
    # a notification is received, the corresponding binary_sensor
    # is briefly toggled.
    - platform: ble_client
      type: characteristic
      ble_client_id: itag_white
      name: 'White iTag btn'
      service_uuid: 'ffe0'
      characteristic_uuid: 'ffe1'
      notify: true
      update_interval: never
      on_notify:
          then:
              - binary_sensor.template.publish:
                    id: white_button
                    state: ON
              - binary_sensor.template.publish:
                    id: white_button
                    state: OFF
    # This entry queries the battery level. Some tags may not
    # support this characteristic, you will see 'Unknown' in the
    # HA frontend.
    - platform: ble_client
      type: characteristic
      ble_client_id: itag_white
      name: 'White iTag Battery'
      service_uuid: '180f'
      characteristic_uuid: '2a19'
      icon: 'mdi:battery'
      unit_of_measurement: '%'
    # This entry queries polls the RSSI when the tag is connected.
    - platform: ble_client
      type: rssi
      ble_client_id: itag_white
      name: 'White iTag RSSI'
