substitutions:
    name: esp32-bluetooth-proxy-2c540c
    friendly_name: Bluetooth Proxy 2c540c
packages:
    esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
    name: ${name}
    name_add_mac_suffix: false
    friendly_name: ${friendly_name}

logger:
    level: DEBUG

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

esp32_ble_tracker:
    scan_parameters:
        interval: 1100ms
        window: 1100ms
        active: true

bluetooth_proxy:
    active: true
